-- Add Microsoft PowerPoint shortcuts
-- Presentation management, slide operations, text editing, and slideshow controls

-- Basic File Operations
INSERT INTO shortcuts (application, keys, description, category, difficulty, platform, windows_keys, macos_keys) VALUES ('powerpoint', 'Ctrl + N', '新しいプレゼンテーションを作成', 'File', 'basic', 'Cross-Platform', 'Ctrl + N', 'Cmd + N') ON CONFLICT (application, keys) DO NOTHING;
INSERT INTO shortcuts (application, keys, description, category, difficulty, platform, windows_keys, macos_keys) VALUES ('powerpoint', 'Ctrl + O', 'プレゼンテーションを開く', 'File', 'basic', 'Cross-Platform', 'Ctrl + O', 'Cmd + O') ON CONFLICT (application, keys) DO NOTHING;
INSERT INTO shortcuts (application, keys, description, category, difficulty, platform, windows_keys, macos_keys) VALUES ('powerpoint', 'Ctrl + S', 'プレゼンテーションを保存', 'File', 'basic', 'Cross-Platform', 'Ctrl + S', 'Cmd + S') ON CONFLICT (application, keys) DO NOTHING;
INSERT INTO shortcuts (application, keys, description, category, difficulty, platform, windows_keys, macos_keys) VALUES ('powerpoint', 'F12', '名前を付けて保存', 'File', 'standard', 'Windows', 'F12', NULL) ON CONFLICT (application, keys) DO NOTHING;
INSERT INTO shortcuts (application, keys, description, category, difficulty, platform, windows_keys, macos_keys) VALUES ('powerpoint', 'Ctrl + P', '印刷', 'File', 'basic', 'Cross-Platform', 'Ctrl + P', 'Cmd + P') ON CONFLICT (application, keys) DO NOTHING;
INSERT INTO shortcuts (application, keys, description, category, difficulty, platform, windows_keys, macos_keys) VALUES ('powerpoint', 'Ctrl + W', 'プレゼンテーションを閉じる', 'File', 'basic', 'Cross-Platform', 'Ctrl + W', 'Cmd + W') ON CONFLICT (application, keys) DO NOTHING;
INSERT INTO shortcuts (application, keys, description, category, difficulty, platform, windows_keys, macos_keys) VALUES ('powerpoint', 'Alt + F4', 'PowerPointを終了', 'File', 'basic', 'Windows', 'Alt + F4', NULL) ON CONFLICT (application, keys) DO NOTHING;

-- Basic Editing
INSERT INTO shortcuts (application, keys, description, category, difficulty, platform, windows_keys, macos_keys) VALUES ('powerpoint', 'Ctrl + C', 'コピー', 'Edit', 'basic', 'Cross-Platform', 'Ctrl + C', 'Cmd + C') ON CONFLICT (application, keys) DO NOTHING;
INSERT INTO shortcuts (application, keys, description, category, difficulty, platform, windows_keys, macos_keys) VALUES ('powerpoint', 'Ctrl + X', '切り取り', 'Edit', 'basic', 'Cross-Platform', 'Ctrl + X', 'Cmd + X') ON CONFLICT (application, keys) DO NOTHING;
INSERT INTO shortcuts (application, keys, description, category, difficulty, platform, windows_keys, macos_keys) VALUES ('powerpoint', 'Ctrl + V', '貼り付け', 'Edit', 'basic', 'Cross-Platform', 'Ctrl + V', 'Cmd + V') ON CONFLICT (application, keys) DO NOTHING;
INSERT INTO shortcuts (application, keys, description, category, difficulty, platform, windows_keys, macos_keys) VALUES ('powerpoint', 'Ctrl + D', '選択したオブジェクトを複製', 'Edit', 'standard', 'Cross-Platform', 'Ctrl + D', 'Cmd + D') ON CONFLICT (application, keys) DO NOTHING;
INSERT INTO shortcuts (application, keys, description, category, difficulty, platform, windows_keys, macos_keys) VALUES ('powerpoint', 'Ctrl + Z', '元に戻す', 'Edit', 'basic', 'Cross-Platform', 'Ctrl + Z', 'Cmd + Z') ON CONFLICT (application, keys) DO NOTHING;
INSERT INTO shortcuts (application, keys, description, category, difficulty, platform, windows_keys, macos_keys) VALUES ('powerpoint', 'Ctrl + Y', 'やり直し', 'Edit', 'basic', 'Cross-Platform', 'Ctrl + Y', 'Cmd + Y') ON CONFLICT (application, keys) DO NOTHING;
INSERT INTO shortcuts (application, keys, description, category, difficulty, platform, windows_keys, macos_keys) VALUES ('powerpoint', 'Ctrl + A', 'すべて選択', 'Edit', 'basic', 'Cross-Platform', 'Ctrl + A', 'Cmd + A') ON CONFLICT (application, keys) DO NOTHING;
INSERT INTO shortcuts (application, keys, description, category, difficulty, platform, windows_keys, macos_keys) VALUES ('powerpoint', 'Delete', '選択したオブジェクトを削除', 'Edit', 'basic', 'Cross-Platform', 'Delete', 'Delete') ON CONFLICT (application, keys) DO NOTHING;

-- Slide Operations
INSERT INTO shortcuts (application, keys, description, category, difficulty, platform, windows_keys, macos_keys) VALUES ('powerpoint', 'Ctrl + M', '新しいスライドを挿入', 'Slide', 'basic', 'Cross-Platform', 'Ctrl + M', 'Cmd + Shift + N') ON CONFLICT (application, keys) DO NOTHING;
INSERT INTO shortcuts (application, keys, description, category, difficulty, platform, windows_keys, macos_keys) VALUES ('powerpoint', 'Ctrl + Shift + D', 'スライドを複製', 'Slide', 'standard', 'Cross-Platform', 'Ctrl + Shift + D', 'Cmd + Shift + D') ON CONFLICT (application, keys) DO NOTHING;
INSERT INTO shortcuts (application, keys, description, category, difficulty, platform, windows_keys, macos_keys) VALUES ('powerpoint', 'Page Up', '前のスライドに移動', 'Slide', 'basic', 'Cross-Platform', 'Page Up', 'Page Up') ON CONFLICT (application, keys) DO NOTHING;
INSERT INTO shortcuts (application, keys, description, category, difficulty, platform, windows_keys, macos_keys) VALUES ('powerpoint', 'Page Down', '次のスライドに移動', 'Slide', 'basic', 'Cross-Platform', 'Page Down', 'Page Down') ON CONFLICT (application, keys) DO NOTHING;
INSERT INTO shortcuts (application, keys, description, category, difficulty, platform, windows_keys, macos_keys) VALUES ('powerpoint', 'Ctrl + ↑', 'スライドを上に移動', 'Slide', 'standard', 'Cross-Platform', 'Ctrl + ↑', 'Cmd + ↑') ON CONFLICT (application, keys) DO NOTHING;
INSERT INTO shortcuts (application, keys, description, category, difficulty, platform, windows_keys, macos_keys) VALUES ('powerpoint', 'Ctrl + ↓', 'スライドを下に移動', 'Slide', 'standard', 'Cross-Platform', 'Ctrl + ↓', 'Cmd + ↓') ON CONFLICT (application, keys) DO NOTHING;
INSERT INTO shortcuts (application, keys, description, category, difficulty, platform, windows_keys, macos_keys) VALUES ('powerpoint', 'Home', '最初のスライドに移動', 'Slide', 'basic', 'Cross-Platform', 'Home', 'Home') ON CONFLICT (application, keys) DO NOTHING;
INSERT INTO shortcuts (application, keys, description, category, difficulty, platform, windows_keys, macos_keys) VALUES ('powerpoint', 'End', '最後のスライドに移動', 'Slide', 'basic', 'Cross-Platform', 'End', 'End') ON CONFLICT (application, keys) DO NOTHING;

-- Slideshow Controls
INSERT INTO shortcuts (application, keys, description, category, difficulty, platform, windows_keys, macos_keys) VALUES ('powerpoint', 'F5', '最初からスライドショーを開始', 'Slideshow', 'basic', 'Cross-Platform', 'F5', 'F5') ON CONFLICT (application, keys) DO NOTHING;
INSERT INTO shortcuts (application, keys, description, category, difficulty, platform, windows_keys, macos_keys) VALUES ('powerpoint', 'Shift + F5', '現在のスライドからスライドショーを開始', 'Slideshow', 'basic', 'Cross-Platform', 'Shift + F5', 'Shift + F5') ON CONFLICT (application, keys) DO NOTHING;
INSERT INTO shortcuts (application, keys, description, category, difficulty, platform, windows_keys, macos_keys) VALUES ('powerpoint', 'Escape', 'スライドショーを終了', 'Slideshow', 'basic', 'Cross-Platform', 'Escape', 'Escape') ON CONFLICT (application, keys) DO NOTHING;
INSERT INTO shortcuts (application, keys, description, category, difficulty, platform, windows_keys, macos_keys) VALUES ('powerpoint', 'Enter', '次のスライドに進む', 'Slideshow', 'basic', 'Cross-Platform', 'Enter', 'Enter') ON CONFLICT (application, keys) DO NOTHING;
INSERT INTO shortcuts (application, keys, description, category, difficulty, platform, windows_keys, macos_keys) VALUES ('powerpoint', 'Space', '次のスライドに進む', 'Slideshow', 'basic', 'Cross-Platform', 'Space', 'Space') ON CONFLICT (application, keys) DO NOTHING;
INSERT INTO shortcuts (application, keys, description, category, difficulty, platform, windows_keys, macos_keys) VALUES ('powerpoint', '→', '次のスライドに進む', 'Slideshow', 'basic', 'Cross-Platform', '→', '→') ON CONFLICT (application, keys) DO NOTHING;
INSERT INTO shortcuts (application, keys, description, category, difficulty, platform, windows_keys, macos_keys) VALUES ('powerpoint', '↓', '次のスライドに進む', 'Slideshow', 'basic', 'Cross-Platform', '↓', '↓') ON CONFLICT (application, keys) DO NOTHING;
INSERT INTO shortcuts (application, keys, description, category, difficulty, platform, windows_keys, macos_keys) VALUES ('powerpoint', 'Backspace', '前のスライドに戻る', 'Slideshow', 'basic', 'Cross-Platform', 'Backspace', 'Backspace') ON CONFLICT (application, keys) DO NOTHING;
INSERT INTO shortcuts (application, keys, description, category, difficulty, platform, windows_keys, macos_keys) VALUES ('powerpoint', '←', '前のスライドに戻る', 'Slideshow', 'basic', 'Cross-Platform', '←', '←') ON CONFLICT (application, keys) DO NOTHING;
INSERT INTO shortcuts (application, keys, description, category, difficulty, platform, windows_keys, macos_keys) VALUES ('powerpoint', '↑', '前のスライドに戻る', 'Slideshow', 'basic', 'Cross-Platform', '↑', '↑') ON CONFLICT (application, keys) DO NOTHING;
INSERT INTO shortcuts (application, keys, description, category, difficulty, platform, windows_keys, macos_keys) VALUES ('powerpoint', 'B', '黒い画面にする/解除', 'Slideshow', 'standard', 'Cross-Platform', 'B', 'B') ON CONFLICT (application, keys) DO NOTHING;
INSERT INTO shortcuts (application, keys, description, category, difficulty, platform, windows_keys, macos_keys) VALUES ('powerpoint', 'W', '白い画面にする/解除', 'Slideshow', 'standard', 'Cross-Platform', 'W', 'W') ON CONFLICT (application, keys) DO NOTHING;
INSERT INTO shortcuts (application, keys, description, category, difficulty, platform, windows_keys, macos_keys) VALUES ('powerpoint', 'S', 'スライドショーを一時停止/再開', 'Slideshow', 'standard', 'Cross-Platform', 'S', 'S') ON CONFLICT (application, keys) DO NOTHING;
INSERT INTO shortcuts (application, keys, description, category, difficulty, platform, windows_keys, macos_keys) VALUES ('powerpoint', 'Ctrl + P', 'ペンツールを使用', 'Slideshow', 'standard', 'Cross-Platform', 'Ctrl + P', 'Cmd + P') ON CONFLICT (application, keys) DO NOTHING;
INSERT INTO shortcuts (application, keys, description, category, difficulty, platform, windows_keys, macos_keys) VALUES ('powerpoint', 'Ctrl + A', '矢印ポインターを使用', 'Slideshow', 'standard', 'Cross-Platform', 'Ctrl + A', 'Cmd + A') ON CONFLICT (application, keys) DO NOTHING;
INSERT INTO shortcuts (application, keys, description, category, difficulty, platform, windows_keys, macos_keys) VALUES ('powerpoint', 'Ctrl + E', '消しゴムツールを使用', 'Slideshow', 'hard', 'Windows', 'Ctrl + E', NULL) ON CONFLICT (application, keys) DO NOTHING;
INSERT INTO shortcuts (application, keys, description, category, difficulty, platform, windows_keys, macos_keys) VALUES ('powerpoint', 'E', 'すべてのインクマークを消去', 'Slideshow', 'hard', 'Cross-Platform', 'E', 'E') ON CONFLICT (application, keys) DO NOTHING;

-- Text Formatting
INSERT INTO shortcuts (application, keys, description, category, difficulty, platform, windows_keys, macos_keys) VALUES ('powerpoint', 'Ctrl + B', '太字', 'Format', 'basic', 'Cross-Platform', 'Ctrl + B', 'Cmd + B') ON CONFLICT (application, keys) DO NOTHING;
INSERT INTO shortcuts (application, keys, description, category, difficulty, platform, windows_keys, macos_keys) VALUES ('powerpoint', 'Ctrl + I', '斜体', 'Format', 'basic', 'Cross-Platform', 'Ctrl + I', 'Cmd + I') ON CONFLICT (application, keys) DO NOTHING;
INSERT INTO shortcuts (application, keys, description, category, difficulty, platform, windows_keys, macos_keys) VALUES ('powerpoint', 'Ctrl + U', '下線', 'Format', 'basic', 'Cross-Platform', 'Ctrl + U', 'Cmd + U') ON CONFLICT (application, keys) DO NOTHING;
INSERT INTO shortcuts (application, keys, description, category, difficulty, platform, windows_keys, macos_keys) VALUES ('powerpoint', 'Ctrl + Shift + >', 'フォントサイズを拡大', 'Format', 'standard', 'Cross-Platform', 'Ctrl + Shift + >', 'Cmd + Shift + >') ON CONFLICT (application, keys) DO NOTHING;
INSERT INTO shortcuts (application, keys, description, category, difficulty, platform, windows_keys, macos_keys) VALUES ('powerpoint', 'Ctrl + Shift + <', 'フォントサイズを縮小', 'Format', 'standard', 'Cross-Platform', 'Ctrl + Shift + <', 'Cmd + Shift + <') ON CONFLICT (application, keys) DO NOTHING;
INSERT INTO shortcuts (application, keys, description, category, difficulty, platform, windows_keys, macos_keys) VALUES ('powerpoint', 'Ctrl + E', '中央揃え', 'Format', 'basic', 'Cross-Platform', 'Ctrl + E', 'Cmd + E') ON CONFLICT (application, keys) DO NOTHING;
INSERT INTO shortcuts (application, keys, description, category, difficulty, platform, windows_keys, macos_keys) VALUES ('powerpoint', 'Ctrl + L', '左揃え', 'Format', 'basic', 'Cross-Platform', 'Ctrl + L', 'Cmd + L') ON CONFLICT (application, keys) DO NOTHING;
INSERT INTO shortcuts (application, keys, description, category, difficulty, platform, windows_keys, macos_keys) VALUES ('powerpoint', 'Ctrl + R', '右揃え', 'Format', 'basic', 'Cross-Platform', 'Ctrl + R', 'Cmd + R') ON CONFLICT (application, keys) DO NOTHING;
INSERT INTO shortcuts (application, keys, description, category, difficulty, platform, windows_keys, macos_keys) VALUES ('powerpoint', 'Ctrl + J', '両端揃え', 'Format', 'standard', 'Cross-Platform', 'Ctrl + J', 'Cmd + J') ON CONFLICT (application, keys) DO NOTHING;

-- Object Manipulation
INSERT INTO shortcuts (application, keys, description, category, difficulty, platform, windows_keys, macos_keys) VALUES ('powerpoint', 'Ctrl + G', 'オブジェクトをグループ化', 'Object', 'standard', 'Cross-Platform', 'Ctrl + G', 'Cmd + Option + G') ON CONFLICT (application, keys) DO NOTHING;
INSERT INTO shortcuts (application, keys, description, category, difficulty, platform, windows_keys, macos_keys) VALUES ('powerpoint', 'Ctrl + Shift + G', 'オブジェクトのグループ化を解除', 'Object', 'standard', 'Cross-Platform', 'Ctrl + Shift + G', 'Cmd + Option + Shift + G') ON CONFLICT (application, keys) DO NOTHING;
INSERT INTO shortcuts (application, keys, description, category, difficulty, platform, windows_keys, macos_keys) VALUES ('powerpoint', 'Ctrl + Shift + C', '書式をコピー', 'Object', 'standard', 'Cross-Platform', 'Ctrl + Shift + C', 'Cmd + Option + C') ON CONFLICT (application, keys) DO NOTHING;
INSERT INTO shortcuts (application, keys, description, category, difficulty, platform, windows_keys, macos_keys) VALUES ('powerpoint', 'Ctrl + Shift + V', '書式を貼り付け', 'Object', 'standard', 'Cross-Platform', 'Ctrl + Shift + V', 'Cmd + Option + V') ON CONFLICT (application, keys) DO NOTHING;
INSERT INTO shortcuts (application, keys, description, category, difficulty, platform, windows_keys, macos_keys) VALUES ('powerpoint', 'Ctrl + Shift + F', '最前面に移動', 'Object', 'hard', 'Windows', 'Ctrl + Shift + F', NULL) ON CONFLICT (application, keys) DO NOTHING;
INSERT INTO shortcuts (application, keys, description, category, difficulty, platform, windows_keys, macos_keys) VALUES ('powerpoint', 'Ctrl + Shift + B', '最背面に移動', 'Object', 'hard', 'Windows', 'Ctrl + Shift + B', NULL) ON CONFLICT (application, keys) DO NOTHING;
INSERT INTO shortcuts (application, keys, description, category, difficulty, platform, windows_keys, macos_keys) VALUES ('powerpoint', 'Shift + ←', 'オブジェクトを左に微調整', 'Object', 'standard', 'Cross-Platform', 'Shift + ←', 'Shift + ←') ON CONFLICT (application, keys) DO NOTHING;
INSERT INTO shortcuts (application, keys, description, category, difficulty, platform, windows_keys, macos_keys) VALUES ('powerpoint', 'Shift + →', 'オブジェクトを右に微調整', 'Object', 'standard', 'Cross-Platform', 'Shift + →', 'Shift + →') ON CONFLICT (application, keys) DO NOTHING;
INSERT INTO shortcuts (application, keys, description, category, difficulty, platform, windows_keys, macos_keys) VALUES ('powerpoint', 'Shift + ↑', 'オブジェクトを上に微調整', 'Object', 'standard', 'Cross-Platform', 'Shift + ↑', 'Shift + ↑') ON CONFLICT (application, keys) DO NOTHING;
INSERT INTO shortcuts (application, keys, description, category, difficulty, platform, windows_keys, macos_keys) VALUES ('powerpoint', 'Shift + ↓', 'オブジェクトを下に微調整', 'Object', 'standard', 'Cross-Platform', 'Shift + ↓', 'Shift + ↓') ON CONFLICT (application, keys) DO NOTHING;

-- View Modes
INSERT INTO shortcuts (application, keys, description, category, difficulty, platform, windows_keys, macos_keys) VALUES ('powerpoint', 'Alt + F5', '発表者ツールでスライドショーを開始', 'View', 'standard', 'Windows', 'Alt + F5', NULL) ON CONFLICT (application, keys) DO NOTHING;
INSERT INTO shortcuts (application, keys, description, category, difficulty, platform, windows_keys, macos_keys) VALUES ('powerpoint', 'Ctrl + F1', 'リボンの表示/非表示', 'View', 'standard', 'Cross-Platform', 'Ctrl + F1', 'Cmd + Option + R') ON CONFLICT (application, keys) DO NOTHING;

-- Navigation in Edit Mode
INSERT INTO shortcuts (application, keys, description, category, difficulty, platform, windows_keys, macos_keys) VALUES ('powerpoint', 'Ctrl + Home', 'プレゼンテーションの先頭に移動', 'Navigation', 'basic', 'Cross-Platform', 'Ctrl + Home', 'Cmd + Home') ON CONFLICT (application, keys) DO NOTHING;
INSERT INTO shortcuts (application, keys, description, category, difficulty, platform, windows_keys, macos_keys) VALUES ('powerpoint', 'Ctrl + End', 'プレゼンテーションの末尾に移動', 'Navigation', 'basic', 'Cross-Platform', 'Ctrl + End', 'Cmd + End') ON CONFLICT (application, keys) DO NOTHING;
INSERT INTO shortcuts (application, keys, description, category, difficulty, platform, windows_keys, macos_keys) VALUES ('powerpoint', 'Ctrl + F', '検索', 'Navigation', 'basic', 'Cross-Platform', 'Ctrl + F', 'Cmd + F') ON CONFLICT (application, keys) DO NOTHING;
INSERT INTO shortcuts (application, keys, description, category, difficulty, platform, windows_keys, macos_keys) VALUES ('powerpoint', 'Ctrl + H', '置換', 'Navigation', 'basic', 'Cross-Platform', 'Ctrl + H', 'Cmd + H') ON CONFLICT (application, keys) DO NOTHING;

-- Insert Elements
INSERT INTO shortcuts (application, keys, description, category, difficulty, platform, windows_keys, macos_keys) VALUES ('powerpoint', 'Ctrl + K', 'ハイパーリンクを挿入', 'Insert', 'standard', 'Cross-Platform', 'Ctrl + K', 'Cmd + K') ON CONFLICT (application, keys) DO NOTHING;
INSERT INTO shortcuts (application, keys, description, category, difficulty, platform, windows_keys, macos_keys) VALUES ('powerpoint', 'Alt + Shift + D', '日付を挿入', 'Insert', 'hard', 'Windows', 'Alt + Shift + D', NULL) ON CONFLICT (application, keys) DO NOTHING;
INSERT INTO shortcuts (application, keys, description, category, difficulty, platform, windows_keys, macos_keys) VALUES ('powerpoint', 'Alt + Shift + T', '時刻を挿入', 'Insert', 'hard', 'Windows', 'Alt + Shift + T', NULL) ON CONFLICT (application, keys) DO NOTHING;
INSERT INTO shortcuts (application, keys, description, category, difficulty, platform, windows_keys, macos_keys) VALUES ('powerpoint', 'Alt + Shift + P', 'スライド番号を挿入', 'Insert', 'hard', 'Windows', 'Alt + Shift + P', NULL) ON CONFLICT (application, keys) DO NOTHING;

-- Tables
INSERT INTO shortcuts (application, keys, description, category, difficulty, platform, windows_keys, macos_keys) VALUES ('powerpoint', 'Tab', '次のセルに移動（表内）', 'Table', 'basic', 'Cross-Platform', 'Tab', 'Tab') ON CONFLICT (application, keys) DO NOTHING;
INSERT INTO shortcuts (application, keys, description, category, difficulty, platform, windows_keys, macos_keys) VALUES ('powerpoint', 'Shift + Tab', '前のセルに移動（表内）', 'Table', 'basic', 'Cross-Platform', 'Shift + Tab', 'Shift + Tab') ON CONFLICT (application, keys) DO NOTHING;

-- Other Useful Shortcuts
INSERT INTO shortcuts (application, keys, description, category, difficulty, platform, windows_keys, macos_keys) VALUES ('powerpoint', 'F1', 'ヘルプを表示', 'Help', 'basic', 'Cross-Platform', 'F1', 'F1') ON CONFLICT (application, keys) DO NOTHING;
INSERT INTO shortcuts (application, keys, description, category, difficulty, platform, windows_keys, macos_keys) VALUES ('powerpoint', 'F7', 'スペルチェック', 'Tools', 'standard', 'Cross-Platform', 'F7', 'F7') ON CONFLICT (application, keys) DO NOTHING;
INSERT INTO shortcuts (application, keys, description, category, difficulty, platform, windows_keys, macos_keys) VALUES ('powerpoint', 'Alt + N', '新しいコメントを挿入', 'Review', 'standard', 'Windows', 'Alt + N', NULL) ON CONFLICT (application, keys) DO NOTHING;
INSERT INTO shortcuts (application, keys, description, category, difficulty, platform, windows_keys, macos_keys) VALUES ('powerpoint', 'Ctrl + T', 'フォントダイアログを開く', 'Format', 'standard', 'Windows', 'Ctrl + T', NULL) ON CONFLICT (application, keys) DO NOTHING;
