-- Migration 039: Update more requested shortcuts
-- This migration updates or adds specific shortcuts based on the user's large list.

INSERT INTO shortcuts (application, keys, description, difficulty)
VALUES
  -- Chrome
  ('chrome', 'Ctrl + Shift + D', 'すべてのタブをブックマークに追加', 'hard'),
  ('chrome', 'Ctrl + Shift + J', 'コンソールを開く', 'hard'),
  ('chrome', 'Ctrl + Shift + Delete', '閲覧データを削除', 'hard'),
  ('chrome', 'Ctrl + Shift + C', '要素を検証', 'hard'),
  ('chrome', 'Ctrl + Shift + M', 'デバイスツールバーの切り替え', 'hard'),
  ('chrome', 'Ctrl + Shift + A', 'タブを検索', 'hard'),
  ('chrome', 'Alt + Home', 'ホームページを開く', 'hard'),
  ('chrome', 'Ctrl + +', '拡大', 'basic'),
  ('chrome', 'Ctrl + -', '縮小', 'basic'),
  ('chrome', 'Space', '1画面下にスクロール', 'basic'),
  ('chrome', 'PageUp', '1画面上にスクロール', 'basic'),
  ('chrome', 'PageDown', '1画面下にスクロール', 'basic'),
  ('chrome', 'Ctrl + ]', 'DevToolsの次のパネルに移動', 'hard'),
  ('chrome', 'Ctrl + [', 'DevToolsの前のパネルに移動', 'hard'),
  ('chrome', 'Shift + F3', '前の検索結果に移動', 'hard'),
  ('chrome', 'Ctrl + Enter', '.comを追加して移動', 'hard'),
  ('chrome', 'Ctrl + Shift + Q', 'Chromeからログアウト', 'hard'),
  ('chrome', 'Ctrl + Shift + V', '書式なしで貼り付け', 'basic'),
  
  -- Excel
  ('excel', 'Ctrl + [', '[移動] 参照元セルに移動', 'basic'),
  ('excel', 'Ctrl + ]', '[移動] 参照先セルに移動', 'hard'),
  ('excel', 'Ctrl + 5', '[書式] 取り消し線', 'hard'),
  ('excel', 'Ctrl + 9', '[表示] 行を非表示', 'hard'),
  ('excel', 'Ctrl + 0', '[表示] 列を非表示', 'hard'),
  ('excel', 'Ctrl + -', '[編集] セル/行/列を削除', 'hard'),
  ('excel', 'Ctrl + Shift + T', '[テーブル] テーブルの合計行を切り替え', 'hard'),
  ('excel', 'Ctrl + 8', '[アウトライン] アウトライン記号の表示/非表示', 'hard'),
  ('excel', 'Alt + F4', '[ファイル] Excelを終了', 'basic'),
  ('excel', 'Shift + Space', '[選択] 行全体を選択', 'basic'),
  ('excel', 'Shift + F2', '[コメント] コメントを挿入/編集', 'hard'),
  ('excel', 'Shift + F3', '[数式] 関数を挿入', 'hard'),
  ('excel', 'Shift + F4', '[検索] 次を検索（検索ダイアログなし）', 'hard'),
  ('excel', 'Shift + F9', '[数式] アクティブシートを再計算', 'hard'),
  ('excel', 'Shift + F10', '[メニュー] コンテキストメニューを表示', 'hard'),
  ('excel', 'Shift + F11', '[その他] 新しいワークシートを挿入', 'hard'),
  ('excel', 'Alt + Enter', '[セル] セル内で改行', 'basic'),
  ('excel', 'Alt + F1', '[データ] グラフを作成（埋め込み）', 'hard'),
  ('excel', 'Ctrl + Space', '[選択] 列全体を選択', 'basic'),
  ('excel', 'Ctrl + ←', '[移動] 左方向の端に移動', 'basic'),
  ('excel', 'Ctrl + →', '[移動] 右方向の端に移動', 'basic'),
  ('excel', 'Ctrl + Q', '[分析] クイック分析', 'hard'),
  ('excel', 'Ctrl + Home', '[移動] A1セルに移動', 'basic'),
  ('excel', 'Ctrl + F1', '[表示] リボンの表示/非表示', 'hard'),
  ('excel', 'Ctrl + F2', '[印刷] 印刷プレビュー', 'hard'),
  ('excel', 'Ctrl + F3', '[名前] 名前の管理', 'hard'),
  ('excel', 'Alt + R + D', '[コメント] コメントを削除', 'hard'),
  ('excel', 'Alt + E + S', '[貼り付け] 形式を選択して貼り付け', 'hard'),
  ('excel', 'Alt + F + T', '[オプション] Excelオプションを開く', 'hard'),
  ('excel', 'Ctrl + ↑', '[移動] 上方向の端に移動', 'basic'),
  ('excel', 'Ctrl + ↓', '[移動] 下方向の端に移動', 'basic'),
  ('excel', 'Ctrl + F6', '[その他] 次のブックウィンドウに切り替え', 'hard'),
  ('excel', 'Ctrl + F9', '[ウィンドウ] ブックウィンドウを最小化', 'hard'),
  ('excel', 'Ctrl + F10', '[ウィンドウ] ブックウィンドウを最大化/復元', 'hard'),
  ('excel', 'Alt + H + H', '[編集] 塗りつぶしの色', 'hard'),
  ('excel', 'Alt + I + R', '[編集] 行を挿入', 'hard'),
  ('excel', 'Alt + I + C', '[編集] 列を挿入', 'hard'),
  ('excel', 'Alt + E + D', '[編集] 行または列を削除', 'hard'),
  ('excel', 'Ctrl + Shift + 5', '[書式] パーセント形式', 'hard'),
  ('excel', 'Ctrl + Shift + 6', '[書式] 指数形式', 'hard'),
  ('excel', 'Ctrl + Shift + 9', '[表示] 行の再表示', 'hard'),
  ('excel', 'Ctrl + Shift + F', '[検索] セルの書式を検索', 'hard'),
  ('excel', 'Ctrl + Shift + O', '[選択] コメントがあるセルを選択', 'hard'),
  ('excel', 'Ctrl + ', '[選択] 行の違いを選択', 'hard'),
  ('excel', 'Ctrl + /', '[選択] アクティブ配列を選択', 'hard'),
  ('excel', 'Alt + ;', '[選択] 可視セルのみを選択', 'hard'),
  
  -- Gmail
  ('gmail', 'Shift + i', '既読にする', 'hard'),
  ('gmail', 'Shift + u', '未読にする', 'hard'),
  ('gmail', 'Shift + c', 'Ccに追加', 'hard'),
  ('gmail', 'Shift + b', 'Bccに追加', 'hard'),
  ('gmail', 'Shift + n', '受信トレイを更新', 'hard'),
  ('gmail', 'Ctrl + s', '下書きを保存', 'hard'),
  ('gmail', 'Shift + Esc', 'フォーカスを外す', 'hard'),
  ('gmail', 'y + o', 'チャットを開く', 'hard'),
  ('gmail', 'p', '前のメッセージ', 'hard'),
  ('gmail', 'u', 'スレッドリストに戻る', 'hard'),
  ('gmail', '{', 'アーカイブしてリストへ戻る', 'hard'),
  ('gmail', 'Ctrl + Shift + C', '[作成] CCに追加', 'hard'),
  ('gmail', 'Ctrl + Shift + B', '[作成] BCCに追加', 'hard'),
  ('gmail', 'm', '[操作] ミュート', 'hard'),
  ('gmail', 'b', '[操作] スヌーズ', 'hard'),
  ('gmail', '#', '削除', 'hard'),
  ('gmail', '_', '[重要] 重要マークを外す', 'hard'),
  ('gmail', 'j', '次のスレッドに移動', 'hard'),
  ('gmail', 'Ctrl + Shift + F', '[検索] メッセージを検索フィルタで検索', 'hard'),
  ('gmail', 'w', '[アクション] タスクに追加', 'hard'),
  ('gmail', 'i', '[アクション] 既読としてマーク', 'hard'),
  ('gmail', 'q', '[アクション] チャット セクションに移動', 'hard'),
  ('gmail', '.', '[その他] その他の操作メニューを表示', 'hard'),
  ('gmail', '`', '[タブ] 次のセクション', 'hard'),
  ('gmail', 'Shift + N', '[アクション] すべて未読にする', 'hard'),
  ('gmail', '~', '[タブ] 前のセクション', 'hard'),
  ('gmail', 'Shift + T', '[アクション] 新しいタブで開く', 'hard'),
  ('gmail', 'Shift + D', '[アクション] 下書きとして保存', 'hard'),
  
  -- PowerPoint
  ('powerpoint', 'Alt + F5', '発表者ツールでスライドショーを開始', 'hard'),
  ('powerpoint', 'Ctrl + F1', 'リボンの表示/非表示', 'hard'),
  ('powerpoint', 'Alt + N', '新しいコメントを挿入', 'hard'),
  
  -- Slack
  ('slack', 'Ctrl + Shift + N', '[基本] 新しい canvas', 'basic'),
  ('slack', 'Shift + Ctrl + M', '[操作方法] アクティビティ', 'basic'),
  ('slack', 'Shift + Ctrl + I', '[操作方法] チャンネル情報', 'basic'),
  ('slack', 'Alt + ←', '[基本] 履歴に戻る', 'basic'),
  ('slack', 'Alt + →', '[基本] 履歴に進む', 'basic'),
  ('slack', 'Shift + Ctrl + T', '[基本] スレッド', 'basic'),
  ('slack', 'Ctrl + +', '[操作方法] テキストサイズを大きくする', 'basic'),
  ('slack', 'Ctrl + -', '[操作方法] テキストサイズを小さくする', 'basic'),
  
  -- Windows 11
  ('windows11', 'Win + Ctrl + N', 'ナレーター設定を開く', 'hard'),
  ('windows11', 'Alt + D', 'アドレスバーを選択', 'hard'),
  ('windows11', 'Win + ,', 'デスクトップを一時的にプレビュー', 'hard'),
  ('windows11', 'Win + C', 'Microsoft Teams チャットを開く', 'hard'),
  ('windows11', 'Win + F', 'フィードバックHubを開く', 'hard'),
  ('windows11', 'Win + K', 'キャスト（ワイヤレスディスプレイ）', 'hard'),
  ('windows11', 'Win + Enter', 'ナレーターを開く', 'hard'),
  ('windows11', 'Win + .', '絵文字パネルを開く', 'hard'),
  ('windows11', 'Win + ;', '絵文字パネルを開く', 'hard'),
  ('windows11', 'Win + O', 'デバイスの向きをロック', 'hard'),
  ('windows11', 'Win + Escape', '拡大鏡を終了', 'hard'),
  ('windows11', 'Win + /', 'IME再変換', 'hard'),
  ('windows11', 'Win + Ctrl + Enter', 'ナレーターを開く', 'hard'),
  ('windows11', 'Ctrl + Shift + E', 'フォルダー内のすべてのフォルダーを展開', 'hard'),
  ('windows11', 'Win + Shift + N', '通知センターとカレンダーを開く', 'hard'),
  ('windows11', 'Alt + Escape', 'ウィンドウを開いた順番で切り替え', 'hard'),
  ('windows11', 'Ctrl + ←', '前の単語の先頭に移動', 'basic'),
  ('windows11', 'Ctrl + →', '次の単語の先頭に移動', 'basic'),
  ('windows11', 'Ctrl + ↑', '前の段落の先頭に移動', 'basic'),
  ('windows11', 'Ctrl + ↓', '次の段落の先頭に移動', 'basic'),
  ('windows11', 'Shift + ←', '1文字左を選択', 'basic'),
  ('windows11', 'Shift + →', '1文字右を選択', 'basic'),
  ('windows11', 'Shift + ↑', '1行上を選択', 'basic'),
  ('windows11', 'Shift + ↓', '1行下を選択', 'basic'),
  ('windows11', 'Ctrl + Home', 'ドキュメントの先頭に移動', 'basic'),
  ('windows11', 'Ctrl + End', 'ドキュメントの末尾に移動', 'basic'),
  ('windows11', 'Shift + Home', '行の先頭まで選択', 'basic'),
  ('windows11', 'Shift + End', '行の末尾まで選択', 'basic'),
  ('windows11', 'Ctrl + Shift + V', 'クリップボード履歴から貼り付け', 'basic'),
  ('windows11', 'Left Alt + Left Shift + Print Screen', 'ハイコントラストのオン/オフ', 'hard'),
  
  -- Word
  ('word', 'Shift + F3', '大文字/小文字を切り替え', 'hard'),
  ('word', 'Ctrl + Space', '書式をクリア', 'hard'),
  ('word', 'Ctrl + Shift + M', '左インデントを減らす', 'hard'),
  ('word', 'Ctrl + Shift + S', 'スタイルを適用', 'hard'),
  ('word', 'Ctrl + ←', '前の単語に移動', 'basic'),
  ('word', 'Ctrl + →', '次の単語に移動', 'basic'),
  ('word', 'Ctrl + ↑', '前の段落に移動', 'basic'),
  ('word', 'Ctrl + ↓', '次の段落に移動', 'basic'),
  ('word', 'Shift + Home', '行の先頭まで選択', 'basic'),
  ('word', 'Shift + End', '行の末尾まで選択', 'basic'),
  ('word', 'Shift + Enter', '改行（段落を分けない）', 'basic')
ON CONFLICT (application, keys) 
DO UPDATE SET 
  description = EXCLUDED.description,
  difficulty = EXCLUDED.difficulty;
